# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1En0PMZUSIMiFl0WfnOlfrV_ubwEAGV7M
"""


import pandas as pd
import streamlit as st
import dill
from app_functions import make_radar, make_ranges



with open('data/not_sorted_defenders.pkl','rb') as f:
    players_stats = pd.read_pickle(f)


params = ['progressive_passes_per90', 'tackles_per90',
 'tackles_won_per90', 'blocks_per90', 'shots_blocked_per90', 'interceptions_per90', 'tackles_interceptions_per90', 'clearances_per90', 'ball_recoveries_per90', 'aerial_duels_per90',
'fouls_committed_per90']



st.header('Compare defenders with Francesco Acerbi', divider='red')
st.write("Choose a defender to compare with Acerbi and at least 3 statistics on which to compare the two players.")

league = st.selectbox(label = 'Select a league', options = list(players_stats['League'].unique()))

if league:
  team = st.selectbox(label = 'Select a team', options = list(players_stats[players_stats['League'] == league]['Team'].unique()))
  if team:
    player = st.selectbox(label = 'Select a player',options=list(players_stats[players_stats['Team'] == team]['Player'].unique()))


    if player:
      st.write(players_stats[players_stats['Player'] == player][['Player','Team','Born', 'Nation'] + params])
      input_params = list(st.multiselect(label = 'Select 3 or more stats on which you want to compare the players', options = list(players_stats.columns)[10:]))
      if len(input_params) >= 3:
        st.pyplot(fig = make_radar('Francesco Acerbi', player,input_params)[0])
      else:
        st.pyplot(fig = make_radar('Francesco Acerbi', player, params)[0])

st.write("The 5 players most similar to Francesco Acerbi are:")
st.write(players_stats.sort_values(by='distance from acerbi')[['Player', 'Team','distance from acerbi']][1:6])

